title: CCDS GSC
logo: /assets/img/logo.png
description: Welcome to the official website of CCDS GSC!
show_downloads: true
google_analytics: G-CJHJXG4C3B
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
