title: CCDS Graduate Students' Club
logo: /assets/img/logo.png
description: Welcome to the official website of the Graduate Students' Club of the College of Computing and Data Science (CCDS) at Nanyang Technological University (NTU), Singapore.
show_downloads: true
google_analytics: G-CJHJXG4C3B
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
